name: Auto Merge

on:
  push
  # schedule:
    # - cron: '25 00 * * *'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install -y gh

    - name: Merge Valid PRs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        YESTERDAY=$(date -d "yesterday" +%y%m%d)
        echo "Yesterday's Date: $YESTERDAY"
      
        # 모든 오픈 PR의 번호와 제목을 가져옴
        echo "Fetching open PRs..."
        PRS=$(gh pr list --state open --json number,title --jq ".[] | select(.title | test(\".+/ $YESTERDAY /.+\")) | .number")
        
        if [[ -z "$PRS" ]]; then
          echo "No PRs matching the criteria were found."
        else
          echo "PRs found, attempting to merge..."
          for PR in $PRS; do
            echo "Attempting to merge PR #$PR"
            MERGE_OUTPUT=$(gh pr merge $PR --merge --auto --admin 2>&1)
            MERGE_STATUS=$?
            if [ $MERGE_STATUS -eq 0 ]; then
              echo "Successfully merged PR #$PR"
            else
              echo "Failed to merge PR #$PR. Error: $MERGE_OUTPUT"
            fi
          done
        fi
