name: Auto Merge

on:
  push
  # schedule:
    # - cron: '25 00 * * *'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install -y gh

    - name: Login GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      run: |
        echo "${GITHUB_TOKEN}" | gh auth login --with-token

    - name: Merge Valid PRs
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      run: |
        YESTERDAY=$(date -d "yesterday" +%y%m%d)
        echo "Yesterday's Date: $YESTERDAY"

        # 모든 오픈 PR의 번호와 제목을 가져옴
        PRS=$(gh pr list --state open --json number,title --jq '.[] | select(.title | test(".+/$YESTERDAY/.+")) | .number')
        
        # 각 PR에 대해 머지 시도
        for PR in $PRS; do
          echo "Merging PR #$PR"
          gh pr merge $PR --merge --auto --admin
        done
