name: Auto Merge

on:
  schedule:
    - cron: '25 00 * * *'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check PR Title
        id: check-title
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          PR_TITLE=$(curl -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" \
            | jq -r '.[0].title')
          echo "PR Title: $PR_TITLE"
          # 예: 'Feature / 210403 / New feature'
          if [[ "$PR_TITLE" =~ ^[^\ ]+\ /[0-9]{6}/ ]]; then
            echo "::set-output name=valid::true"
          else
            echo "::set-output name=valid::false"
          fi
      
      - name: Auto Merge PRs
        if: steps.check-title.outputs.valid == 'true'
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          MERGE_LABELS: "" # 자동 머지할 PR에 특정 라벨이 필요한 경우 여기에 지정
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title" # PR 제목을 커밋 메시지로 사용
