name: Auto Merge

on:
  schedule:
    - cron: '25 00 * * *'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Auto Merge PRs
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          MERGE_LABELS: "" # 자동 머지할 PR에 특정 라벨이 필요한 경우 여기에 지정
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title" # PR 제목을 커밋 메시지로 사용
